# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test_train_model',
                'doc_host': 'https://daveramsey-ze.github.io',
                'git_url': 'https://github.com/daveramsey-ze/nbdev_test_train_model',
                'lib_path': 'nbdev_test_train_model'},
  'syms': {'nbdev_test_train_model.core': {'nbdev_test_train_model.core.foo': ('core.html#foo', 'nbdev_test_train_model/core.py')}}}
